POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Yet another blog post",
    "author": "Some Blogger",
    "url": "www.blog.com/these-will-never-stop",
    "likes": 3
}